import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Caveat } from "next/font/google";
import { Mali } from 'next/font/google'
import { Fuzzy_Bubbles } from 'next/font/google'

import { Patrick_Hand } from 'next/font/google';
import "./globals.css";
import "./styles.scss"; 


const inter = Inter({ subsets: ["latin"] });
const caveat = Caveat({ subsets: ["latin"] });
const fuzzyBubbles = Fuzzy_Bubbles({ 
  subsets: ["latin"],
  weight: ["400", "700"] 
});


const mali = Mali({ 
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '700'],
  style: ['normal', 'italic'],
});

const patrickHand = Patrick_Hand({ 
  subsets: ["latin"],
  weight: ['400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fuzzyBubbles.className}>{children}</body>
    </html>
  );
}
